name: image_network
description: Image Network is a package that allows you to render images on the web using CanvasKit without having problems with CORS
version: 2.5.1
homepage: https://github.com/gabrielpatricksouza/image_network

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  http: ">=0.13.4 <1.0.0"
  webviewimage: ">=0.0.1 <1.0.0"

dependency_overrides:
  webviewimage:
    git: https://github.com/Prn-Ice/webviewimage.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
